In [21]:
clfs = ["CART", "EBM", "LR_l2", "GNB", "LR", "DL"]
dataset_names = ['breast', 'campus', 'churn', 'climate',
            'compas', 'diabetes', 'german', 'heart',
            'adult', 'student', 'bank', 'credit']

dataset_names_cart = ['breast', 'churn', 'compas', 'diabetes',
                      'heart', 'adult', 'bank', 'credit']

In [2]:
import numpy as np
import pandas as pd

In [22]:
clf_n = 5
dataset_n = 12
dataset_dl_n = 8

### CART generator

In [18]:
clf_names_cart = ["EBM", "LR_l2", "GNB", "LR", "DL"] 

In [5]:
results_cart = np.load(f'../test_results/acc_fidelity_res/auc_results_{clfs[0]}.npy')
print("\nScores:\n", results_cart.shape)

mean_results_cart = np.mean(results_cart, axis=2).T
print("\nMean results:\n", mean_results_cart)

from scipy.stats import rankdata
ranks_cart = []
for mr in mean_results_cart:
    ranks_cart.append(rankdata(mr).tolist())
ranks_cart = np.array(ranks_cart)
print("\nRanks:\n", ranks_cart)

mean_ranks_cart = np.mean(ranks_cart, axis=0)
mean_ranks_cart


Scores:
 (5, 12, 10)

Mean results:
 [[0.96071068 0.97088023 0.9257684  0.95712843 0.92681457]
 [0.83428571 0.82833333 0.74809524 0.84047619 0.53690476]
 [0.7251629  0.58751781 0.6596794  0.58788254 0.67504435]
 [0.6        0.81697959 0.71297959 0.82441837 0.5       ]
 [0.86368026 0.68169285 0.73417893 0.68169285 0.7919974 ]
 [0.70537037 0.73139316 0.72405983 0.72939316 0.72859544]
 [0.66160455 0.67374741 0.67024845 0.67516563 0.5       ]
 [0.7732381  0.78621429 0.78084524 0.7885119  0.719     ]
 [0.79438539 0.76725923 0.69613415 0.76725443 0.73287384]
 [0.64820474 0.68368772 0.66743485 0.67732153 0.50555556]
 [0.70005165 0.66000264 0.70265968 0.6602862  0.68188161]
 [0.88084428 0.87087986 0.69917077 0.86689381 0.87017515]]

Ranks:
 [[4.  5.  1.  3.  2. ]
 [4.  3.  2.  5.  1. ]
 [5.  1.  3.  2.  4. ]
 [2.  4.  3.  5.  1. ]
 [5.  1.5 3.  1.5 4. ]
 [1.  5.  2.  4.  3. ]
 [2.  4.  3.  5.  1. ]
 [2.  4.  3.  5.  1. ]
 [5.  4.  1.  3.  2. ]
 [2.  5.  3.  4.  1. ]
 [4.  1.  5.  2.  3. ]
 [5

array([3.41666667, 3.45833333, 2.5       , 3.45833333, 2.16666667])

In [19]:
pd.DataFrame(mean_ranks_cart, index=clf_names_cart).T

EBM     LR_l2  GNB        LR        DL
0  3.416667  3.458333  2.5  3.458333  2.166667

#### bias and variance 

In [63]:
# get bias and variance accross all datasets and clfs
results_bias_cart = []
for clf_name in clf_names_cart:
    res_df = pd.read_csv(f"../test_results/acc_fidelity_res/CART/{clf_name}.csv")
    results_bias_cart.append(res_df)


final_results_bias_cart = np.zeros(shape=(clf_n, dataset_n))
final_results_var_cart = np.zeros(shape=(clf_n, dataset_n))

for clf_id, clf_name in enumerate(clf_names_cart):
    for dataset_id, dataset_name in enumerate(dataset_names):
        res_df_cart = results_bias_cart[clf_id]
        res_dataset_df = res_df_cart[res_df_cart["dataset_name"] == dataset_name]
        final_results_bias_cart[clf_id, dataset_id] = res_dataset_df.describe().iloc[1][1]
        final_results_var_cart[clf_id, dataset_id] = res_dataset_df.describe().iloc[1][2]  
        

In [72]:
final_results_bias_cart[0]

array([0.44870269, 0.35641515, 0.26757809, 0.09066251, 0.30725562,
       0.38477855, 0.31368805, 0.44884313, 0.33096236, 0.36642416,
       0.16654259, 0.46953688])

In [73]:
final_results_bias_cart[1]

array([0.45814728, 0.38469155, 0.2410139 , 0.11473658, 0.28740577,
       0.40832612, 0.33764565, 0.46066253, 0.33609287, 0.38469185,
       0.16183654, 0.47224216])

In [74]:
final_results_bias_cart[2]

array([0.45900662, 0.34324827, 0.27983168, 0.1001361 , 0.31799261,
       0.41302759, 0.43292795, 0.46979646, 0.59954392, 0.40313231,
       0.22055441, 0.40398407])

In [75]:
final_results_bias_cart[3]

array([0.4502288 , 0.37520127, 0.2412035 , 0.13262281, 0.28727723,
       0.40881426, 0.33691729, 0.45775216, 0.33593103, 0.37588182,
       0.16199617, 0.45707239])

In [76]:
final_results_bias_cart[4]

array([0.45819379, 0.30781562, 0.26443163, 0.08517983, 0.3060735 ,
       0.40266402, 0.29976729, 0.44458341, 0.32492219, 0.44603573,
       0.17044358, 0.49006575])

In [64]:
pd.DataFrame(final_results_bias_cart.T)

ranks_bias_cart = []
for mr in final_results_bias_cart.T:
    ranks_bias_cart.append(rankdata(mr).tolist())
ranks_bias_cart = np.array(ranks_bias_cart)
ranks_bias_cart = len(ranks_bias_cart[0])+1 - ranks_bias_cart.astype(int)
print("\nRanks:\n", ranks_bias_cart)

mean_ranks_bias_cart = np.mean(ranks_bias_cart, axis=0)
mean_ranks_bias_cart



Ranks:
 [[5 3 1 4 2]
 [3 1 4 2 5]
 [2 5 1 4 3]
 [4 2 3 1 5]
 [2 4 1 5 3]
 [5 3 1 2 4]
 [4 2 1 3 5]
 [4 2 1 3 5]
 [4 2 1 3 5]
 [5 3 2 4 1]
 [3 5 1 4 2]
 [3 2 5 4 1]]


array([3.66666667, 2.83333333, 1.83333333, 3.25      , 3.41666667])

In [77]:
np.subtract(mean_ranks_cart, mean_ranks_bias_cart)

array([-0.25      ,  0.625     ,  0.66666667,  0.20833333, -1.25      ])

In [78]:
final_acc_bias_cart = np.array([ 0      ,  0.625     ,  0.66666667,  0.20833333, 0])

In [79]:
pd.DataFrame(final_acc_bias_cart, index=clf_names_cart).T

EBM  LR_l2       GNB        LR   DL
0  0.0  0.625  0.666667  0.208333  0.0