In [1]:
clfs = ["CART", "EBM", "LR_l2", "GNB", "LR", "DL"]
dataset_names = ['breast', 'campus', 'churn', 'climate',
            'compas', 'diabetes', 'german', 'heart',
            'adult', 'student', 'bank', 'credit']

dataset_names_dl = ['breast', 'churn', 'compas', 'diabetes',
                      'heart', 'adult', 'bank', 'credit']

In [2]:
import numpy as np
import pandas as pd

In [3]:
clf_n = 5
dataset_n = 12
dataset_dl_n = 8

### CART generator

In [4]:
clf_names_cart = ["EBM", "LR_l2", "GNB", "LR", "DL"] 

In [5]:
results_cart = np.load(f'../test_results/acc_fidelity_res/auc_results_{clfs[0]}.npy')
print("\nScores:\n", results_cart.shape)

mean_results_cart = np.mean(results_cart, axis=2).T
print("\nMean results:\n", mean_results_cart)

from scipy.stats import rankdata
ranks_cart = []
for mr in mean_results_cart:
    ranks_cart.append(rankdata(mr).tolist())
ranks_cart = np.array(ranks_cart)
print("\nRanks:\n", ranks_cart)

mean_ranks_cart = np.mean(ranks_cart, axis=0)
mean_ranks_cart


Scores:
 (5, 12, 10)

Mean results:
 [[0.96071068 0.97088023 0.9257684  0.95712843 0.92681457]
 [0.83428571 0.82833333 0.74809524 0.84047619 0.53690476]
 [0.7251629  0.58751781 0.6596794  0.58788254 0.67504435]
 [0.6        0.81697959 0.71297959 0.82441837 0.5       ]
 [0.86368026 0.68169285 0.73417893 0.68169285 0.7919974 ]
 [0.70537037 0.73139316 0.72405983 0.72939316 0.72859544]
 [0.66160455 0.67374741 0.67024845 0.67516563 0.5       ]
 [0.7732381  0.78621429 0.78084524 0.7885119  0.719     ]
 [0.79438539 0.76725923 0.69613415 0.76725443 0.73287384]
 [0.64820474 0.68368772 0.66743485 0.67732153 0.50555556]
 [0.70005165 0.66000264 0.70265968 0.6602862  0.68188161]
 [0.88084428 0.87087986 0.69917077 0.86689381 0.87017515]]

Ranks:
 [[4.  5.  1.  3.  2. ]
 [4.  3.  2.  5.  1. ]
 [5.  1.  3.  2.  4. ]
 [2.  4.  3.  5.  1. ]
 [5.  1.5 3.  1.5 4. ]
 [1.  5.  2.  4.  3. ]
 [2.  4.  3.  5.  1. ]
 [2.  4.  3.  5.  1. ]
 [5.  4.  1.  3.  2. ]
 [2.  5.  3.  4.  1. ]
 [4.  1.  5.  2.  3. ]
 [5

array([3.41666667, 3.45833333, 2.5       , 3.45833333, 2.16666667])

In [6]:
pd.DataFrame(mean_ranks_cart, index=clf_names_cart).T

EBM     LR_l2  GNB        LR        DL
0  3.416667  3.458333  2.5  3.458333  2.166667

#### bias and variance 

In [7]:
# get bias and variance accross all datasets and clfs
results_bias_cart = []
for clf_name in clf_names_cart:
    res_df = pd.read_csv(f"../test_results/acc_fidelity_res/CART/{clf_name}.csv")
    results_bias_cart.append(res_df)


final_results_bias_cart = np.zeros(shape=(clf_n, dataset_n))
final_results_var_cart = np.zeros(shape=(clf_n, dataset_n))

for clf_id, clf_name in enumerate(clf_names_cart):
    for dataset_id, dataset_name in enumerate(dataset_names):
        res_df_cart = results_bias_cart[clf_id]
        res_dataset_df = res_df_cart[res_df_cart["dataset_name"] == dataset_name]
        final_results_bias_cart[clf_id, dataset_id] = res_dataset_df.describe().iloc[1][1]
        final_results_var_cart[clf_id, dataset_id] = res_dataset_df.describe().iloc[1][2]  
        

In [8]:
final_results_bias_cart[0]

array([0.44870269, 0.35641515, 0.26757809, 0.09066251, 0.30725562,
       0.38477855, 0.31368805, 0.44884313, 0.33096236, 0.36642416,
       0.16654259, 0.46953688])

In [9]:
final_results_bias_cart[1]

array([0.45814728, 0.38469155, 0.2410139 , 0.11473658, 0.28740577,
       0.40832612, 0.33764565, 0.46066253, 0.33609287, 0.38469185,
       0.16183654, 0.47224216])

In [10]:
final_results_bias_cart[2]

array([0.45900662, 0.34324827, 0.27983168, 0.1001361 , 0.31799261,
       0.41302759, 0.43292795, 0.46979646, 0.59954392, 0.40313231,
       0.22055441, 0.40398407])

In [11]:
final_results_bias_cart[3]

array([0.4502288 , 0.37520127, 0.2412035 , 0.13262281, 0.28727723,
       0.40881426, 0.33691729, 0.45775216, 0.33593103, 0.37588182,
       0.16199617, 0.45707239])

In [12]:
final_results_bias_cart[4]

array([0.45819379, 0.30781562, 0.26443163, 0.08517983, 0.3060735 ,
       0.40266402, 0.29976729, 0.44458341, 0.32492219, 0.44603573,
       0.17044358, 0.49006575])

In [13]:
pd.DataFrame(final_results_bias_cart.T)

ranks_bias_cart = []
for mr in final_results_bias_cart.T:
    ranks_bias_cart.append(rankdata(mr).tolist())
ranks_bias_cart = np.array(ranks_bias_cart)
ranks_bias_cart = len(ranks_bias_cart[0])+1 - ranks_bias_cart.astype(int)
print("\nRanks:\n", ranks_bias_cart)

mean_ranks_bias_cart = np.mean(ranks_bias_cart, axis=0)
mean_ranks_bias_cart



Ranks:
 [[5 3 1 4 2]
 [3 1 4 2 5]
 [2 5 1 4 3]
 [4 2 3 1 5]
 [2 4 1 5 3]
 [5 3 1 2 4]
 [4 2 1 3 5]
 [4 2 1 3 5]
 [4 2 1 3 5]
 [5 3 2 4 1]
 [3 5 1 4 2]
 [3 2 5 4 1]]


array([3.66666667, 2.83333333, 1.83333333, 3.25      , 3.41666667])

In [14]:
np.subtract(mean_ranks_cart, mean_ranks_bias_cart)

array([-0.25      ,  0.625     ,  0.66666667,  0.20833333, -1.25      ])

In [15]:
final_acc_bias_cart = np.array([ 0      ,  0.625     ,  0.66666667,  0.20833333, 0])

In [16]:
pd.DataFrame(final_acc_bias_cart, index=clf_names_cart).T

EBM  LR_l2       GNB        LR   DL
0  0.0  0.625  0.666667  0.208333  0.0

### EBM generator

In [17]:
clf_names_ebm = ["CART", "LR_l2", "GNB", "LR", "DL"] 
results_ebm = np.load(f'../test_results/acc_fidelity_res/auc_results_{clfs[1]}.npy')
print("\nScores:\n", results_ebm.shape)

mean_results_ebm = np.mean(results_ebm, axis=2).T
print("\nMean results:\n", mean_results_ebm)

from scipy.stats import rankdata
ranks_ebm = []
for mr in mean_results_ebm:
    ranks_ebm.append(rankdata(mr).tolist())
ranks_ebm = np.array(ranks_ebm)
print("\nRanks:\n", ranks_ebm)

mean_ranks_ebm = np.mean(ranks_ebm, axis=0)
mean_ranks_ebm


Scores:
 (5, 12, 10)

Mean results:
 [[0.91590909 0.97088023 0.9257684  0.95712843 0.92681457]
 [0.79       0.82833333 0.74809524 0.84047619 0.53690476]
 [0.94649328 0.67456559 0.74935789 0.67569886 0.85882901]
 [0.68771429 0.81697959 0.71297959 0.82441837 0.5       ]
 [0.9997342  0.96956596 0.95667769 0.99982285 0.86698976]
 [0.86027056 0.86796537 0.84999459 0.87034632 0.82700216]
 [0.76822755 0.86177757 0.77197043 0.87456478 0.5       ]
 [0.88211905 0.92428571 0.91595238 0.91164286 0.86871429]
 [0.93758855 0.90625434 0.74266489 0.90691091 0.83057514]
 [0.67920833 0.80733333 0.78191667 0.80004167 0.50979167]
 [0.89253552 0.83882165 0.83254986 0.83944322 0.78527201]
 [0.92368212 0.93184964 0.78097678 0.92492184 0.92551188]]

Ranks:
 [[1. 5. 2. 4. 3.]
 [3. 4. 2. 5. 1.]
 [5. 1. 3. 2. 4.]
 [2. 4. 3. 5. 1.]
 [4. 3. 2. 5. 1.]
 [3. 4. 2. 5. 1.]
 [2. 4. 3. 5. 1.]
 [2. 5. 4. 3. 1.]
 [5. 3. 1. 4. 2.]
 [2. 5. 3. 4. 1.]
 [5. 3. 2. 4. 1.]
 [2. 5. 1. 3. 4.]]


array([3.        , 3.83333333, 2.33333333, 4.08333333, 1.75      ])

In [18]:
pd.DataFrame(mean_ranks_ebm, index=clf_names_ebm).T

CART     LR_l2       GNB        LR    DL
0   3.0  3.833333  2.333333  4.083333  1.75

In [19]:
# get bias and variance accross all datasets and clfs
results_bias_ebm = []
for clf_name in clf_names_ebm:
    res_df = pd.read_csv(f"../test_results/acc_fidelity_res/EBM/{clf_name}.csv")
    results_bias_ebm.append(res_df)


final_results_bias_ebm = np.zeros(shape=(clf_n, dataset_n))
final_results_var_ebm = np.zeros(shape=(clf_n, dataset_n))

for clf_id, clf_name in enumerate(clf_names_ebm):
    for dataset_id, dataset_name in enumerate(dataset_names):
        res_df_ebm = results_bias_ebm[clf_id]
        res_dataset_df = res_df_ebm[res_df_ebm["dataset_name"] == dataset_name]
        final_results_bias_ebm[clf_id, dataset_id] = res_dataset_df.describe().iloc[1][1]
        final_results_var_ebm[clf_id, dataset_id] = res_dataset_df.describe().iloc[1][2]  
        

In [20]:
pd.DataFrame(final_results_bias_ebm.T)

ranks_bias_ebm = []
for mr in final_results_bias_ebm.T:
    ranks_bias_ebm.append(rankdata(mr).tolist())
ranks_bias_ebm = np.array(ranks_bias_ebm)
ranks_bias_ebm = len(ranks_bias_ebm[0])+1 - ranks_bias_ebm.astype(int)
print("\nRanks:\n", ranks_bias_ebm)

mean_ranks_bias_ebm = np.mean(ranks_bias_ebm, axis=0)
mean_ranks_bias_ebm


Ranks:
 [[5 3 1 4 2]
 [4 1 3 2 5]
 [2 5 3 4 1]
 [3 2 4 1 5]
 [2 4 1 3 5]
 [5 2 3 4 1]
 [4 2 1 3 5]
 [5 1 3 2 4]
 [4 2 1 3 5]
 [5 1 4 2 3]
 [4 3 1 2 5]
 [4 2 5 3 1]]


array([3.91666667, 2.33333333, 2.5       , 2.75      , 3.5       ])

In [21]:
np.subtract(mean_ranks_ebm, mean_ranks_bias_ebm)

array([-0.91666667,  1.5       , -0.16666667,  1.33333333, -1.75      ])

In [22]:
final_acc_bias_ebm = np.array([ 0,  1.5       , 0,  1.33333333, 0])

In [23]:
pd.DataFrame(final_acc_bias_ebm, index=clf_names_ebm).T

CART  LR_l2  GNB        LR   DL
0   0.0    1.5  0.0  1.333333  0.0

### LR_l2 generator

In [24]:
clf_names_lr_l2 = ["CART", "EBM", "GNB", "LR", "DL"] 
results_lr_l2 = np.load(f'../test_results/acc_fidelity_res/auc_results_{clfs[2]}.npy')
print("\nScores:\n", results_lr_l2.shape)

mean_results_lr_l2 = np.mean(results_lr_l2, axis=2).T
print("\nMean results:\n", mean_results_lr_l2)

from scipy.stats import rankdata
ranks_lr_l2 = []
for mr in mean_results_lr_l2:
    ranks_lr_l2.append(rankdata(mr).tolist())
ranks_lr_l2 = np.array(ranks_lr_l2)
print("\nRanks:\n", ranks_lr_l2)

mean_ranks_lr_l2 = np.mean(ranks_lr_l2, axis=0)
mean_ranks_lr_l2


Scores:
 (5, 12, 10)

Mean results:
 [[0.93718254 0.96059524 0.93380952 0.99007937 0.93650794]
 [0.81845238 0.93044643 0.80282738 0.96758929 0.5       ]
 [0.94562791 0.95859702 0.87870321 0.99408626 0.74906346]
 [0.67394118 0.59285294 0.71985294 0.95122549 0.5       ]
 [0.99838272 0.99764727 0.81819358 0.99973545 0.80787498]
 [0.87590368 0.94103896 0.90528139 0.99017857 0.88987013]
 [0.78813201 0.91597602 0.84762889 0.96321393 0.5       ]
 [0.93728745 0.96479757 0.91954453 0.98204453 0.88216599]
 [0.94041697 0.98736321 0.773278   0.99642703 0.88386056]
 [0.75871963 0.87361466 0.82166454 0.90286658 0.51725277]
 [0.935699   0.97411801 0.8612715  0.99694053 0.87129287]
 [0.95544508 0.97258523 0.91543561 0.98011364 0.95904356]]

Ranks:
 [[3. 4. 1. 5. 2.]
 [3. 4. 2. 5. 1.]
 [3. 4. 2. 5. 1.]
 [3. 2. 4. 5. 1.]
 [4. 3. 2. 5. 1.]
 [1. 4. 3. 5. 2.]
 [2. 4. 3. 5. 1.]
 [3. 4. 2. 5. 1.]
 [3. 4. 1. 5. 2.]
 [2. 4. 3. 5. 1.]
 [3. 4. 1. 5. 2.]
 [2. 4. 1. 5. 3.]]


array([2.66666667, 3.75      , 2.08333333, 5.        , 1.5       ])

In [25]:
pd.DataFrame(mean_ranks_lr_l2, index=clf_names_lr_l2).T

CART   EBM       GNB   LR   DL
0  2.666667  3.75  2.083333  5.0  1.5

In [26]:
# get bias and variance accross all datasets and clfs
results_bias_lr_l2 = []
for clf_name in clf_names_lr_l2:
    res_df = pd.read_csv(f"../test_results/acc_fidelity_res/LR_l2/{clf_name}.csv")
    results_bias_lr_l2.append(res_df)


final_results_bias_lr_l2 = np.zeros(shape=(clf_n, dataset_n))
final_results_var_lr_l2 = np.zeros(shape=(clf_n, dataset_n))

for clf_id, clf_name in enumerate(clf_names_lr_l2):
    for dataset_id, dataset_name in enumerate(dataset_names):
        res_df_lr_l2 = results_bias_lr_l2[clf_id]
        res_dataset_df = res_df_lr_l2[res_df_lr_l2["dataset_name"] == dataset_name]
        final_results_bias_lr_l2[clf_id, dataset_id] = res_dataset_df.describe().iloc[1][1]
        final_results_var_lr_l2[clf_id, dataset_id] = res_dataset_df.describe().iloc[1][2]  
        

In [27]:
pd.DataFrame(final_results_bias_lr_l2.T)

ranks_bias_lr_l2 = []
for mr in final_results_bias_lr_l2.T:
    ranks_bias_lr_l2.append(rankdata(mr).tolist())
ranks_bias_lr_l2 = np.array(ranks_bias_lr_l2)
ranks_bias_lr_l2 = len(ranks_bias_lr_l2[0])+1 - ranks_bias_lr_l2.astype(int)
print("\nRanks:\n", ranks_bias_lr_l2)

mean_ranks_bias_lr_l2 = np.mean(ranks_bias_lr_l2, axis=0)
mean_ranks_bias_lr_l2


Ranks:
 [[5 4 3 2 1]
 [4 2 3 1 5]
 [4 3 1 2 5]
 [3 4 2 1 5]
 [4 3 1 2 5]
 [5 4 3 1 2]
 [4 3 1 2 5]
 [5 2 3 1 4]
 [5 3 1 2 4]
 [5 3 2 1 4]
 [5 3 1 2 4]
 [4 2 5 3 1]]


array([4.41666667, 3.        , 2.16666667, 1.66666667, 3.75      ])

In [28]:
np.subtract(mean_ranks_lr_l2, mean_ranks_bias_lr_l2)

array([-1.75      ,  0.75      , -0.08333333,  3.33333333, -2.25      ])

In [29]:
final_acc_bias_lr_l2 = np.array([0      ,  0.75      , 0,  3.33333333, 0      ])

In [30]:
pd.DataFrame(final_acc_bias_lr_l2, index=clf_names_lr_l2).T

CART   EBM  GNB        LR   DL
0   0.0  0.75  0.0  3.333333  0.0

### GNB generator

In [31]:
clf_names_gnb = ["CART", "EBM", "LR_l2", "LR", "DL"] 
results_gnb = np.load(f'../test_results/acc_fidelity_res/auc_results_{clfs[3]}.npy')
print("\nScores:\n", results_gnb.shape)

mean_results_gnb = np.mean(results_gnb, axis=2).T
print("\nMean results:\n", mean_results_gnb)

from scipy.stats import rankdata
ranks_gnb = []
for mr in mean_results_gnb:
    ranks_gnb.append(rankdata(mr).tolist())
ranks_gnb = np.array(ranks_gnb)
print("\nRanks:\n", ranks_gnb)

mean_ranks_gnb = np.mean(ranks_gnb, axis=0)
mean_ranks_gnb


Scores:
 (5, 12, 10)

Mean results:
 [[0.94951308 0.98535714 0.96344166 0.95780459 0.94151544]
 [0.82482143 0.91720238 0.90803571 0.96785714 0.5       ]
 [0.95934092 0.97692897 0.90173047 0.9036407  0.8463934 ]
 [0.73235294 0.68235294 0.88039216 0.90882353 0.5       ]
 [0.99689092 0.99844833 0.99094426 0.99207413 0.88724386]
 [0.88484887 0.94480238 0.93062751 0.93091463 0.86549676]
 [0.78418579 0.95918562 0.93435644 0.95681209 0.4994084 ]
 [0.92693398 0.96231494 0.94489719 0.9576342  0.88787121]
 [0.98408389 0.99392331 0.97825363 0.99480194 0.5       ]
 [0.8645     0.90992857 0.93339286 0.92047619 0.5102381 ]
 [0.95715053 0.98252266 0.95800245 0.9650574  0.76785847]
 [0.88572506 0.93263575 0.93834842 0.93420868 0.89011258]]

Ranks:
 [[2. 5. 4. 3. 1.]
 [2. 4. 3. 5. 1.]
 [4. 5. 2. 3. 1.]
 [3. 2. 4. 5. 1.]
 [4. 5. 2. 3. 1.]
 [2. 5. 3. 4. 1.]
 [2. 5. 3. 4. 1.]
 [2. 5. 3. 4. 1.]
 [3. 4. 2. 5. 1.]
 [2. 3. 5. 4. 1.]
 [2. 5. 3. 4. 1.]
 [1. 3. 5. 4. 2.]]


array([2.41666667, 4.25      , 3.25      , 4.        , 1.08333333])

In [32]:
pd.DataFrame(mean_ranks_gnb, index=clf_names_gnb).T

CART   EBM  LR_l2   LR        DL
0  2.416667  4.25   3.25  4.0  1.083333

In [33]:
# get bias and variance accross all datasets and clfs
results_bias_gnb= []
for clf_name in clf_names_gnb:
    res_df = pd.read_csv(f"../test_results/acc_fidelity_res/GNB/{clf_name}.csv")
    results_bias_gnb.append(res_df)


final_results_bias_gnb = np.zeros(shape=(clf_n, dataset_n))
final_results_var_gnb = np.zeros(shape=(clf_n, dataset_n))

for clf_id, clf_name in enumerate(clf_names_gnb):
    for dataset_id, dataset_name in enumerate(dataset_names):
        res_df_gnb = results_bias_gnb[clf_id]
        res_dataset_df = res_df_gnb[res_df_gnb["dataset_name"] == dataset_name]
        final_results_bias_gnb[clf_id, dataset_id] = res_dataset_df.describe().iloc[1][1]
        final_results_var_gnb[clf_id, dataset_id] = res_dataset_df.describe().iloc[1][2]  
        

In [34]:
pd.DataFrame(final_results_bias_gnb.T)

ranks_bias_gnb = []
for mr in final_results_bias_gnb.T:
    ranks_bias_gnb.append(rankdata(mr).tolist())
ranks_bias_gnb = np.array(ranks_bias_gnb)
ranks_bias_gnb = len(ranks_bias_gnb[0])+1 - ranks_bias_gnb.astype(int)
print("\nRanks:\n", ranks_bias_gnb)

mean_ranks_bias_gnb = np.mean(ranks_bias_gnb, axis=0)
mean_ranks_bias_gnb


Ranks:
 [[5 3 2 4 1]
 [4 3 2 1 5]
 [4 1 3 2 5]
 [3 4 2 1 5]
 [5 3 2 4 1]
 [5 4 2 1 3]
 [5 3 1 2 4]
 [5 3 1 2 4]
 [4 2 3 1 5]
 [4 2 1 3 5]
 [4 2 3 1 5]
 [5 4 3 2 1]]


array([4.41666667, 2.83333333, 2.08333333, 2.        , 3.66666667])

In [35]:
np.subtract(mean_ranks_gnb, mean_ranks_bias_gnb)

array([-2.        ,  1.41666667,  1.16666667,  2.        , -2.58333333])

In [36]:
final_acc_bias_gnb = np.array([0,  1.41666667,  1.16666667,  2.        , 0])

In [37]:
pd.DataFrame(final_acc_bias_gnb, index=clf_names_gnb).T

CART       EBM     LR_l2   LR   DL
0   0.0  1.416667  1.166667  2.0  0.0

### LR generator

In [38]:
clf_names_lr = ["CART", "EBM", "LR_l2", "GNB", "DL"] 
results_lr = np.load(f'../test_results/acc_fidelity_res/auc_results_{clfs[4]}.npy')
print("\nScores:\n", results_lr.shape)

mean_results_lr = np.mean(results_lr, axis=2).T
print("\nMean results:\n", mean_results_lr)

from scipy.stats import rankdata
ranks_lr = []
for mr in mean_results_lr:
    ranks_lr.append(rankdata(mr).tolist())
ranks_lr = np.array(ranks_lr)
print("\nRanks:\n", ranks_lr)

mean_ranks_lr = np.mean(ranks_lr, axis=0)
mean_ranks_lr


Scores:
 (5, 12, 10)

Mean results:
 [[0.93248918 0.96785714 0.97685426 0.92621934 0.93861111]
 [0.83309524 0.92809524 0.96571429 0.81238095 0.50714286]
 [0.94562791 0.95859702 0.97751152 0.87870321 0.74906346]
 [0.65295098 0.58135294 0.87916667 0.69901961 0.5       ]
 [0.99838272 0.99764727 0.99331414 0.81819358 0.80787498]
 [0.89458333 0.91910714 0.97517857 0.90327381 0.89386905]
 [0.76773684 0.91638158 0.9349386  0.81864912 0.50208333]
 [0.9216336  0.9667753  0.96269231 0.92502834 0.88462146]
 [0.93893897 0.98749896 0.98882197 0.76661897 0.88250361]
 [0.77205301 0.91155909 0.92650474 0.79243345 0.50995844]
 [0.93760899 0.97737672 0.98513495 0.86175666 0.87223156]
 [0.93261924 0.95161793 0.95621074 0.76458109 0.93843834]]

Ranks:
 [[2. 4. 5. 1. 3.]
 [3. 4. 5. 2. 1.]
 [3. 4. 5. 2. 1.]
 [3. 2. 5. 4. 1.]
 [5. 4. 3. 2. 1.]
 [2. 4. 5. 3. 1.]
 [2. 4. 5. 3. 1.]
 [2. 5. 4. 3. 1.]
 [3. 4. 5. 1. 2.]
 [2. 4. 5. 3. 1.]
 [3. 4. 5. 1. 2.]
 [2. 4. 5. 1. 3.]]


array([2.66666667, 3.91666667, 4.75      , 2.16666667, 1.5       ])

In [39]:
pd.DataFrame(mean_ranks_lr, index=clf_names_lr).T

CART       EBM  LR_l2       GNB   DL
0  2.666667  3.916667   4.75  2.166667  1.5

In [40]:
# get bias and variance accross all datasets and clfs
results_bias_lr = []
for clf_name in clf_names_lr:
    res_df = pd.read_csv(f"../test_results/acc_fidelity_res/LR/{clf_name}.csv")
    results_bias_lr.append(res_df)


final_results_bias_lr = np.zeros(shape=(clf_n, dataset_n))
final_results_var_lr = np.zeros(shape=(clf_n, dataset_n))

for clf_id, clf_name in enumerate(clf_names_lr):
    for dataset_id, dataset_name in enumerate(dataset_names):
        res_df_lr = results_bias_lr[clf_id]
        res_dataset_df = res_df_lr[res_df_lr["dataset_name"] == dataset_name]
        final_results_bias_lr[clf_id, dataset_id] = res_dataset_df.describe().iloc[1][1]
        final_results_var_lr[clf_id, dataset_id] = res_dataset_df.describe().iloc[1][2]  
        

In [41]:
pd.DataFrame(final_results_bias_lr.T)

ranks_bias_lr = []
for mr in final_results_bias_lr.T:
    ranks_bias_lr.append(rankdata(mr).tolist())
ranks_bias_lr = np.array(ranks_bias_lr)
ranks_bias_lr = len(ranks_bias_lr[0])+1 - ranks_bias_lr.astype(int)
print("\nRanks:\n", ranks_bias_lr)

mean_ranks_bias_lr = np.mean(ranks_bias_lr, axis=0)
mean_ranks_bias_lr


Ranks:
 [[5 4 2 3 1]
 [4 2 1 3 5]
 [4 3 2 1 5]
 [2 4 1 3 5]
 [4 3 2 1 5]
 [5 4 2 3 1]
 [4 3 2 1 5]
 [5 2 1 4 3]
 [5 3 2 1 4]
 [5 2 1 4 3]
 [5 3 2 1 4]
 [4 3 2 5 1]]


array([4.33333333, 3.        , 1.66666667, 2.5       , 3.5       ])

In [42]:
np.subtract(mean_ranks_lr, mean_ranks_bias_lr)

array([-1.66666667,  0.91666667,  3.08333333, -0.33333333, -2.        ])

In [43]:
final_acc_bias_lr = np.array([0,  0.91666667,  3.08333333, 0, 0])

In [44]:
pd.DataFrame(final_acc_bias_lr, index=clf_names_lr).T

CART       EBM     LR_l2  GNB   DL
0   0.0  0.916667  3.083333  0.0  0.0

### DL generator

In [45]:
clf_names_dl = ["CART", "EBM", "LR_l2", "GNB", "LR"]
results_dl = np.load(f'../test_results/acc_fidelity_res/auc_results_{clfs[5]}.npy')
print("\nScores:\n", results_dl.shape)

mean_results_dl = np.mean(results_dl, axis=2).T
print("\nMean results:\n", mean_results_dl)

from scipy.stats import rankdata
ranks_dl = []
for mr in mean_results_dl:
    ranks_dl.append(rankdata(mr).tolist())
ranks_dl = np.array(ranks_dl)
print("\nRanks:\n", ranks_dl)

mean_ranks_dl = np.mean(ranks_dl, axis=0)
mean_ranks_dl[:-1]


Scores:
 (6, 8, 10)

Mean results:
 [[0.96154867 0.97005299 0.96819538 0.92952947 0.9556576  0.        ]
 [1.         1.         0.77422546 0.86001147 0.77783191 0.        ]
 [1.         0.99918699 1.         0.99918699 0.99989858 0.        ]
 [0.98548265 0.97779035 0.94288989 0.88581599 0.94473756 0.        ]
 [0.95399374 0.94812253 0.91763011 0.89275362 0.93022069 0.        ]
 [1.         0.99943467 0.99197968 0.77924443 0.9932277  0.        ]
 [0.99983713 0.99891653 0.99374393 0.89338678 0.99827905 0.        ]
 [1.         1.         0.9983871  1.         0.9983871  0.        ]]

Ranks:
 [[4.  6.  5.  2.  3.  1. ]
 [5.5 5.5 2.  4.  3.  1. ]
 [5.5 2.5 5.5 2.5 4.  1. ]
 [6.  5.  3.  2.  4.  1. ]
 [6.  5.  3.  2.  4.  1. ]
 [6.  5.  3.  2.  4.  1. ]
 [6.  5.  3.  2.  4.  1. ]
 [5.  5.  2.5 5.  2.5 1. ]]


array([5.5   , 4.875 , 3.375 , 2.6875, 3.5625])

In [46]:
pd.DataFrame(mean_ranks_dl[:-1], index=clf_names_dl).T

CART    EBM  LR_l2     GNB      LR
0   5.5  4.875  3.375  2.6875  3.5625

In [47]:
# get bias and variance accross all datasets and clfs
results_bias_dl = []
for clf_name in clf_names_dl:
    res_df = pd.read_csv(f"../test_results/acc_fidelity_res/DL/{clf_name}.csv")
    results_bias_dl.append(res_df)


final_results_bias_dl = np.zeros(shape=(clf_n, dataset_n))
final_results_var_dl = np.zeros(shape=(clf_n, dataset_n))

for clf_id, clf_name in enumerate(clf_names_dl):
    for dataset_id, dataset_name in enumerate(dataset_names_dl):
        res_df_dl = results_bias_dl[clf_id]
        res_dataset_df = res_df_dl[res_df_dl["dataset_name"] == dataset_name]
        final_results_bias_dl[clf_id, dataset_id] = res_dataset_df.describe().iloc[1][1]
        final_results_var_dl[clf_id, dataset_id] = res_dataset_df.describe().iloc[1][2]  
        

In [48]:
pd.DataFrame(final_results_bias_dl.T)

ranks_bias_dl = []
for mr in final_results_bias_dl.T:
    ranks_bias_dl.append(rankdata(mr).tolist())
ranks_bias_dl = np.array(ranks_bias_dl)
ranks_bias_dl = len(ranks_bias_dl[0])+1 - ranks_bias_dl.astype(int)
print("\nRanks:\n", ranks_bias_dl)

mean_ranks_bias_dl = np.mean(ranks_bias_dl, axis=0)
mean_ranks_bias_dl


Ranks:
 [[5 3 2 1 4]
 [2 2 5 3 4]
 [1 4 3 5 2]
 [3 1 4 5 2]
 [5 4 2 1 3]
 [2 5 4 1 3]
 [2 3 5 1 4]
 [2 2 5 2 5]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


array([2.83333333, 3.        , 3.5       , 2.58333333, 3.25      ])

In [49]:
np.subtract(mean_ranks_dl[:-1], mean_ranks_bias_dl)

array([ 2.66666667,  1.875     , -0.125     ,  0.10416667,  0.3125    ])

In [50]:
final_acc_bias_dl = np.array([2.66666667,  1.875     , 0   ,  0.10416667,  0.3125])

In [51]:
pd.DataFrame(final_acc_bias_dl, index=clf_names_dl).T

CART    EBM  LR_l2       GNB      LR
0  2.666667  1.875    0.0  0.104167  0.3125

## Final Results

In [52]:
cart_1 = final_acc_bias_ebm[0]
ebm_1 = final_acc_bias_cart[0]
lr_l2_1 = final_acc_bias_cart[1]
gnb_1 = final_acc_bias_cart[2]
lr_1 = final_acc_bias_cart[3]
dl_1 = final_acc_bias_cart[4]

cart_2 = final_acc_bias_lr_l2[0]
ebm_2 = final_acc_bias_lr_l2[1]
lr_l2_2 = final_acc_bias_ebm[1]
gnb_2 = final_acc_bias_ebm[2]
lr_2 = final_acc_bias_ebm[3]
dl_2 = final_acc_bias_ebm[4]

cart_3 = final_acc_bias_gnb[0]
ebm_3 = final_acc_bias_gnb[1]
lr_l2_3 = final_acc_bias_gnb[2]
gnb_3 = final_acc_bias_lr_l2[3]
lr_3 = final_acc_bias_gnb[3]
dl_3 = final_acc_bias_lr_l2[4]

cart_4 = final_acc_bias_lr[0]
ebm_4 = final_acc_bias_lr[1]
lr_l2_4 = final_acc_bias_lr[2]
gnb_4 = final_acc_bias_lr[3]
lr_4 = final_acc_bias_lr_l2[3]
dl_4 = final_acc_bias_gnb[4]

cart_5 = final_acc_bias_dl[0]
ebm_5 = final_acc_bias_dl[1]
lr_l2_5 = final_acc_bias_dl[2]
gnb_5 = final_acc_bias_dl[3]
lr_5 = final_acc_bias_dl[4]
dl_5 = final_acc_bias_lr[4]

In [53]:
cart_list = [cart_1, cart_2, cart_3, cart_4, cart_5]
cart_fin = pd.DataFrame(cart_list).T.mean(axis=1)

gnb_list = [gnb_1, gnb_2, gnb_3, gnb_4, gnb_5]
gnb_fin = pd.DataFrame(gnb_list).T.mean(axis=1)

lr_list = [lr_1, lr_2, lr_3, lr_4, lr_5]
lr_fin = pd.DataFrame(lr_list).T.mean(axis=1)

lr_l2_list = [lr_l2_1, lr_l2_2, lr_l2_3, lr_l2_4, lr_l2_5]
lr_l2_fin = pd.DataFrame(lr_l2_list).T.mean(axis=1)

dl_list = [dl_1, dl_2, dl_3, dl_4, dl_5]
dl_fin = pd.DataFrame(dl_list).T.mean(axis=1)

ebm_list = [ebm_1, ebm_2, ebm_3, ebm_4, ebm_5]
ebm_fin = pd.DataFrame(ebm_list).T.mean(axis=1)

In [54]:
cart_fin

0    0.533333
dtype: float64

In [55]:
cart_list

[0.0, 0.0, 0.0, 0.0, 2.66666667]

In [56]:
gnb_list

[0.66666667, 0.0, 3.33333333, 0.0, 0.10416667]

In [57]:
gnb_fin

0    0.820833
dtype: float64

In [58]:
lr_fin

0    1.4375
dtype: float64

In [59]:
lr_list

[0.20833333, 1.33333333, 2.0, 3.33333333, 0.3125]

In [60]:
lr_l2_fin

0    1.275
dtype: float64

In [61]:
lr_l2_list

[0.625, 1.5, 1.16666667, 3.08333333, 0.0]

In [62]:
dl_fin

0    0.0
dtype: float64

In [63]:
dl_list

[0.0, 0.0, 0.0, 0.0, 0.0]

In [64]:
ebm_fin

0    0.991667
dtype: float64

In [65]:
ebm_list

[0.0, 0.75, 1.41666667, 0.91666667, 1.875]

In [69]:
pd.DataFrame((cart_fin, ebm_fin, gnb_fin, lr_fin, lr_l2_fin, dl_fin)).T

0         1         2       3      4    5
0  0.533333  0.991667  0.820833  1.4375  1.275  0.0