In [1]:
clf_names = ["CART", "EBM", "GNB", "LR", "LR_l2", "DL"]
dataset_names = ['breast', 'campus', 'churn', 'climate',
            'compas', 'diabetes', 'german', 'heart',
            'adult', 'student', 'bank', 'credit']

In [57]:
import pandas as pd 
import numpy as np

## CART GENERATOR

In [87]:
def scale_values(worst, best, value):
    y = [0, 100]
    x = [worst, best]
    coeffs = np.polyfit(x, y, 1)
    return coeffs[0]*value + coeffs[1]

In [102]:
clf_list_cart = ["EBM", "GNB", "LR", "LR_l2", "DL"]
clf_n = len(clf_list_cart)
dataset_n = len(dataset_names)
cart_results = np.zeros(shape=(dataset_n, clf_n))
cart_scaled_results = np.zeros(shape=(dataset_n, clf_n))

clf_name_gen = "CART"

for data_id, dataset in enumerate(dataset_names):
    result_df = pd.read_csv(f"../worst-case_results/{dataset}_{clf_name_gen}.csv")
    result_df = result_df.drop(clf_name_gen, axis=1)

    result_df = result_df.groupby(by="Param").mean()

    for clf_id, clf_name in enumerate(clf_list_cart):
        cart_results[data_id, clf_id] = result_df[clf_name].sum()
    
    
    best = cart_results[data_id].min()
    worst = cart_results[data_id].max()

    for i in range(len(cart_results[data_id])):
        value = np.abs(np.round(scale_values(worst, best, value=cart_results[data_id][i]), decimals=2))
        cart_scaled_results[data_id, i] = value
        

In [103]:
cart_scaled_results

array([[100.  ,  57.92,  39.2 ,  74.33,   0.  ],
       [100.  ,  83.76,  88.58,  91.03,   0.  ],
       [100.  ,  45.08,   5.78,   0.  ,  49.08],
       [ 97.26, 100.  ,  90.91,  95.67,   0.  ],
       [100.  ,   0.  ,  88.9 ,  88.79,  31.9 ],
       [ 92.68,   0.  , 100.  ,  86.8 ,  17.4 ],
       [100.  ,  13.5 ,  82.91,  87.06,   0.  ],
       [100.  ,  69.23,  95.67,  97.5 ,   0.  ],
       [100.  ,   0.  ,  87.91,  88.1 ,  81.87],
       [100.  ,  64.54,  97.03,  98.67,   0.  ],
       [100.  ,   0.  ,  72.46,  72.85,  98.45],
       [100.  ,   0.  ,  50.61,  51.98,  26.76]])

In [95]:
cart_scaled_results

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -2.84217094e-14],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -2.84217094e-14],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  4.90792561e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -2.84217094e-14],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  3.18982496e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.73977009e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -4.26325641e-14],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.84217094e-14],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  8.18690213e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00

In [90]:
cart_results[0].min()

62.64075517152763

In [77]:
cart_results[0].min()

62.64075517152763

In [3]:
#breast dataset 
data_breast_CART = pd.read_csv("../worst-case_results/breast_CART.csv")
data_breast_CART

Param  CART       EBM         LR       GNB     LR_l2  \
0                radius_mean   0.0  0.195020   9.422959  9.349021  4.883782   
1                radius_mean   0.0  0.195020   9.422959  9.349021  4.883782   
2                radius_mean   0.0  0.195020   9.422959  9.349021  4.883782   
3                radius_mean   0.0  0.195020   9.422959  9.349021  4.883782   
4                radius_mean   0.0  0.195020   9.422959  9.349021  4.883782   
..                       ...   ...       ...        ...       ...       ...   
205  fractal_dimension_worst   0.0  1.120746  35.767341  7.600761  8.722950   
206  fractal_dimension_worst   0.0  1.120746  35.767341  7.600761  8.722950   
207  fractal_dimension_worst   0.0  1.120746  35.767341  7.600761  8.722950   
208  fractal_dimension_worst   0.0  1.120746  35.767341  7.600761  8.722950   
209  fractal_dimension_worst   0.0  1.120746  35.767341  7.600761  8.722950   

            DL  
0    24.688340  
1    24.688340  
2    24.688340  
3    24.688340  
4    24.688340  
..         ...  
205  24.789462  
206  24.789462  
207  24.789462  
208  24.789462  
209  24.789462  

[210 rows x 7 columns]

In [13]:
data_breast_CART= data_breast_CART.groupby(by="Param").mean()

In [14]:
data_breast_CART

CART        EBM         LR        GNB      LR_l2  \
Param                                                                       
area_mean                 0.0   0.772576   8.404504  29.044750   6.591166   
area_se                   0.0   3.983296  48.495681  49.886755  25.871133   
area_worst                0.0   1.593617  43.835454  38.229475  14.022897   
compactness_mean          0.0   0.301277  11.695050   6.061822   2.729369   
compactness_se            0.0   0.103929  28.131728   3.025329   3.274163   
compactness_worst         0.0   0.310255   2.070140  10.456759   3.596867   
concave points_mean       0.0   0.444918  15.603792  19.533878   9.291577   
concave points_se         0.0   0.111134  39.080843   2.564935   6.145560   
concave points_worst      0.0  10.276343  12.290484   7.142884   7.232682   
concavity_mean            0.0   0.424166  38.801399   9.326985   9.088397   
concavity_se              0.0   0.413740  20.736722   5.536654   2.383535   
concavity_worst           0.0   3.979193  14.567222   7.266017  11.471262   
fractal_dimension_mean    0.0   0.080694   4.655149   1.844793   2.560574   
fractal_dimension_se      0.0   0.310008  21.684962   3.409047   4.902401   
fractal_dimension_worst   0.0   1.120746  35.767341   7.600761   8.722950   
perimeter_mean            0.0   0.794737   6.132566  10.880101   4.865063   
perimeter_se              0.0   0.311196  13.956921  43.061434  16.379189   
perimeter_worst           0.0   1.547904  24.573527  21.513893   8.276958   
radius_mean               0.0   0.195020   9.422959   9.349021   4.883782   
radius_se                 0.0   0.445012  40.342155  40.797099  30.233591   
radius_worst              0.0  24.020153  11.514619  17.346394  16.754221   
smoothness_mean           0.0   0.803180  10.528609   1.382744   3.630929   
smoothness_se             0.0   0.358429   4.240238   1.496088   6.916538   
smoothness_worst          0.0   4.247307   6.015503   5.935087   9.158468   
symmetry_mean             0.0   0.278813   3.268921   2.256384   3.616361   
symmetry_se               0.0   0.296436   3.337404   4.684619   2.008985   
symmetry_worst            0.0   0.895531  18.027261   8.874873  11.944116   
texture_mean              0.0   0.412761   2.421144   2.207118   4.897744   
texture_se                0.0   0.167062   3.870246   1.311749   2.251284   
texture_worst             0.0   3.641323  12.361007   4.231511  10.256224   

                                DL  
Param                               
area_mean                24.688340  
area_se                  27.213261  
area_worst               55.130190  
compactness_mean         24.901674  
compactness_se           24.787583  
compactness_worst        24.688340  
concave points_mean      34.433076  
concave points_se        24.688340  
concave points_worst     38.453412  
concavity_mean           24.585143  
concavity_se             24.552247  
concavity_worst          26.702111  
fractal_dimension_mean   24.688340  
fractal_dimension_se     24.811114  
fractal_dimension_worst  24.789462  
perimeter_mean           24.688340  
perimeter_se             24.690753  
perimeter_worst          32.106187  
radius_mean              24.688340  
radius_se                24.688340  
radius_worst             19.089655  
smoothness_mean          24.422056  
smoothness_se            25.025007  
smoothness_worst         28.590395  
symmetry_mean            24.771952  
symmetry_se              24.688340  
symmetry_worst           24.825007  
texture_mean             24.827772  
texture_se               24.688340  
texture_worst            27.102519

In [16]:
data_breast_CART["EBM"].sum()

62.64075517152763

In [17]:
data_breast_CART["LR"].sum()

515.8335524653005

In [18]:
data_breast_CART["LR_l2"].sum()

253.95798819980158

In [19]:
data_breast_CART["GNB"].sum()

376.2589558962798

In [20]:
data_breast_CART["DL"].sum()

808.0056410478002

In [21]:
best = data_breast_CART["EBM"].sum()
worst = data_breast_CART["DL"].sum()

In [46]:
best

62.64075517152763

In [47]:
worst

808.0056410478002

In [51]:
y = [0, 100]
x = [worst, best]
coeffs = np.polyfit(x, y, 1)

In [52]:
coeffs

array([ -0.13416248, 108.40403893])

In [53]:
a = coeffs[0]
b = coeffs[1]

In [58]:
def scale_values(worst, best, value):
    y = [0, 100]
    x = [worst, best]
    coeffs = np.polyfit(x, y, 1)
    return coeffs[0]*value + coeffs[1]

In [59]:
scale_values(worst, best, value=data_breast_CART["LR"].sum())

39.19853136615279